version: '3.7'

services:
  # Start docker container for PostgreSQL to mock RDS
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always

  # Start docker container for Datacube-Index
  index:
    image: opendatacube/datacube-index
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - AWS_DEFAULT_REGION=af-south-1
      - STAC_API_URL=https://earth-search.aws.element84.com/v0/
    volumes:
      - .:/code
    depends_on:
      - postgres
    command: tail -f /dev/null
